grpc:
  client:
    user-service:
      address: static//192.168.100.3:6565
      negotiationType: plaintext

    movie-service:
       address: static/192.168.100.3:7565
       negotiationType: plaintext